### ISSUE TITLE
GR Version 1.18.0: undefined symbol: gr_inqorthographicprojection

### ISSUE THREAD

**Issue by EmDash00** [sciapp/python-gr#26]
I updated from 1.17.3 to 1.18.0 using pip and encountered this error. This prevents me from using qtgr as well since qtgr imports gr3. I uninstalled and downloaded 1.17.3 and sure enough importing gr3 works. 

Here's the traceback
```
>>> import gr3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr3/__init__.py", line 145, in <module>
    _gr3 = load_runtime()
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr3/__init__.py", line 124, in load_runtime
    return CDLL(library_filename)
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr/lib/libGR3.so: undefined symbol: gr_inqorthographicprojection
```

My system specs are:

OS: Ubuntu 20.04.3 LTS
Kernel: Linux 5.4.0-84-generic
CPU: Intel  i7-8550U W 4.000 GHz
GPU: Intel UHD Graphics 620

Let me know if you need anything else.

**Comment by FlorianRhiem** [comment]
Hello @EmDash00,

thank you for reporting this issue. It looks like libGR3.so depends on those symbols but cannot find them. They should be contained in `libGR.so`, which `libGR3.so` should load as well.

Are you able to `import gr` instead of gr3?

If so, then are you able to import gr3 after importing gr first?

If not, you may need to update your installation of the GR runtime. You can try uninstalling `gr` and reinstalling it, or you can download the latest version from here: https://gr-framework.org/downloads/gr-latest-Ubuntu-x86_64.tar.gz and replace the files at `/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr/lib/`.

**Comment by EmDash00** [comment]
Yes, I'm able to `import gr`
```
>>> import gr
>>> gr.inqorthographicprojection
<function inqorthographicprojection at 0x7f4e6c89e430>
>>> import gr3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr3/__init__.py", line 145, in <module>
    _gr3 = load_runtime()
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr3/__init__.py", line 124, in load_runtime
    return CDLL(library_filename)
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr/lib/libGR3.so: undefined symbol: gr_inqorthographicprojection
```

I've tried uninstalling and reinstalling gr with no luck.

**Comment by EmDash00** [comment]
Yes, I'm able to `import gr`
```
>>> import gr
>>> gr.inqorthographicprojection
<function inqorthographicprojection at 0x7f4e6c89e430>
>>> import gr3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr3/__init__.py", line 145, in <module>
    _gr3 = load_runtime()
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr3/__init__.py", line 124, in load_runtime
    return CDLL(library_filename)
  File "/home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/emdash00/.pyenv/versions/3.8.12/lib/python3.8/site-packages/gr/lib/libGR3.so: undefined symbol: gr_inqorthographicprojection
```

I've tried uninstalling and reinstalling gr with no luck. I also tried again in a python virtual environment with no luck. I've tested on other systems and it seems to work fine, so I'm not sure what's the problem.

**Comment by FlorianRhiem** [comment]
What is the output of `gr.version()`?

**Comment by EmDash00** [comment]
```
>>> gr.version()
'Runtime: 0.58.0 / Python: 1.18.0'
```

**Comment by FlorianRhiem** [comment]
Okay, that seems odd. The GR library with runtime version 0.58.0 should definitely have that symbol. My suspicion is that perhaps when loading libGR3, an older libGR might be found and loaded from your system. Something you could try would be setting the environment variable `LD_LIBRARY_PATH` to the directory containing the up-to-date libGR when starting python, to see if that libGR is loaded along with libGR3 that way.

**Comment by EmDash00** [comment]
That seems to be the problem. I got another chance to check my LD_LIBRARY_PATH and saw a old version of GR I tried to install in `/usr/local/lib`. Thanks for the tip.
